/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.OpstiDomenskiObjekat;
import domen.Radnik;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import niti.StartServer;
import tabela.TblModelRadnik;

/**
 *
 * @author Nadin kompjuter
 */
public class FMGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FMGlavna
     */
    List<OpstiDomenskiObjekat> lista_radnika;

    public FMGlavna() {
        initComponents();
        srediFormu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JTextField();
        jbtnTestirajKonekciju = new javax.swing.JButton();
        jbtnPokreniServer = new javax.swing.JButton();
        jlStatus = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtDriver = new javax.swing.JTextField();
        jtxtUrl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRadnici = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Password");

        jtxtUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtUsername.setEnabled(false);

        jtxtPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtPassword.setEnabled(false);

        jbtnTestirajKonekciju.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnTestirajKonekciju.setText("Testiraj konekciju");
        jbtnTestirajKonekciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTestirajKonekcijuActionPerformed(evt);
            }
        });

        jbtnPokreniServer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnPokreniServer.setText("Pokreni server program");
        jbtnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPokreniServerActionPerformed(evt);
            }
        });

        jlStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlStatus.setForeground(new java.awt.Color(255, 0, 0));
        jlStatus.setText("Server nije pokrenut!");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Izaberi bazu:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Driver:");

        jtxtDriver.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtDriver.setEnabled(false);

        jtxtUrl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtUrl.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Url:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtUrl)
                                    .addComponent(jComboBox1, 0, 132, Short.MAX_VALUE)
                                    .addComponent(jtxtDriver)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtUsername)
                                    .addComponent(jtxtPassword)))
                            .addComponent(jbtnTestirajKonekciju)
                            .addComponent(jlStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jbtnPokreniServer)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnTestirajKonekciju)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jbtnPokreniServer)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Podesavanja", jPanel1);

        jtblRadnici.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtblRadnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblRadnici);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Dodaj radnika");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Radnici", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPokreniServerActionPerformed
        StartServer ss = new StartServer();
        ss.start();

        jlStatus.setText("Server program je pokrenut");
        jlStatus.setForeground(new java.awt.Color(0, 255, 0));
        jbtnPokreniServer.setEnabled(false);

    }//GEN-LAST:event_jbtnPokreniServerActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            if (jComboBox1.getSelectedItem().equals("MySQL")) {
                util.Util.getInstance().setCurrent_db("mysql");
                jtxtUrl.setText(util.Util.getInstance().getUrl());
                jtxtDriver.setText(util.Util.getInstance().getDriver());
                jtxtUsername.setText(util.Util.getInstance().getUser());
                jtxtPassword.setText(util.Util.getInstance().getPassword());

            }
            if (jComboBox1.getSelectedItem().equals("Access")) {
                util.Util.getInstance().setCurrent_db("access");
                jtxtUrl.setText(util.Util.getInstance().getUrl());
                jtxtDriver.setText(util.Util.getInstance().getDriver());
                jtxtUsername.setText(util.Util.getInstance().getUser());
                jtxtPassword.setText(util.Util.getInstance().getPassword());

            }
        } catch (IOException iOException) {
        }


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jbtnTestirajKonekcijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTestirajKonekcijuActionPerformed

        try {
            kontrolor.KontrolorAL.getInstance().testirajKonekciju();
            JOptionPane.showMessageDialog(this, "Uspesna konekcija!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }


    }//GEN-LAST:event_jbtnTestirajKonekcijuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FMRadnik fmr = new FMRadnik(this, true, lista_radnika);
        fmr.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnPokreniServer;
    private javax.swing.JButton jbtnTestirajKonekciju;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JTable jtblRadnici;
    private javax.swing.JTextField jtxtDriver;
    private javax.swing.JTextField jtxtPassword;
    private javax.swing.JTextField jtxtUrl;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables


    private void srediFormu() {
        try {
            List<OpstiDomenskiObjekat> lr = kontrolor.KontrolorAL.getInstance().vratiSveRadnike(this);
            TblModelRadnik tmr = new TblModelRadnik(lr);
            jtblRadnici.setModel(tmr);
            lista_radnika = lr;
            jComboBox1.addItem("MySQL");
            jComboBox1.addItem("Access");
        } catch (Exception ex) {
            Logger.getLogger(FMGlavna.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void promeniStatusRadniku(Radnik radnik) {
        TblModelRadnik tmr = (TblModelRadnik) jtblRadnici.getModel();
        tmr.promeniStatusRadniku(radnik);
    }

    void azurirajTabelu(Radnik r) {
        lista_radnika.add(r);
        TblModelRadnik tmr = new TblModelRadnik(lista_radnika);
        jtblRadnici.setModel(tmr);
    }

    public void postaviStatuseNaOffline() {
        for (OpstiDomenskiObjekat odo : lista_radnika) {
            Radnik r = (Radnik)odo;
            r.setStatus("Offline");
            promeniStatusRadniku(r);
        }
        
    }
    public boolean daLiJeRadnikVecPrijavljen(OpstiDomenskiObjekat r) {
        for (OpstiDomenskiObjekat radnik : lista_radnika) {
            Radnik rad = (Radnik)radnik;
            Radnik rad2 = (Radnik)r;
            if(rad.getRadnikID().equals(rad2.getRadnikID()) && rad.getStatus().equalsIgnoreCase("online")){
            return true;}
        }
        return false;
    }

    
}
