/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.OpstiDomenskiObjekat;
import domen.Radnik;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Nadin kompjuter
 */
public class FMRadnik extends javax.swing.JDialog {

    /**
     * Creates new form FMRadnik
     */
    List<OpstiDomenskiObjekat> lista_ranika;
    FMGlavna fmGlavna;

    public FMRadnik(java.awt.Frame parent, boolean modal, List<OpstiDomenskiObjekat> lr) {
        super(parent, modal);
        fmGlavna =(FMGlavna) parent;
        lista_ranika = lr;
        initComponents();
        srediFormu();
        postaviDocumentListenerIme();
        postaviDocumentListenerPrezime();
        postaviDocumentListenerUser();
        postaviDocumentListenerPass();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtRadnikID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtIme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtPrezime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtPass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtDatumZaposlenja = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jErrorIme = new javax.swing.JLabel();
        jErrorPrezime = new javax.swing.JLabel();
        jErrorUser = new javax.swing.JLabel();
        jErrorPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos radnika");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Sifra radnika:");

        jtxtRadnikID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtRadnikID.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Ime:");

        jtxtIme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Prezime:");

        jtxtPrezime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Datum zaposlenja:");

        jtxtUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Username:");

        jtxtPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPassActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Password:");

        jtxtDatumZaposlenja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtDatumZaposlenja.setEnabled(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Dodaj radnika");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jErrorIme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jErrorPrezime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jErrorUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jErrorPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jtxtRadnikID, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDatumZaposlenja, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxtPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(jtxtUser, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtIme, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtPrezime, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jErrorPrezime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(jErrorIme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jErrorUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jErrorPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtRadnikID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDatumZaposlenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jErrorIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jErrorPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jErrorUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jErrorPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jtxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPassActionPerformed


    }//GEN-LAST:event_jtxtPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!jErrorIme.getText().trim().equals("") || !jErrorPrezime.getText().trim().equals("")
                || !jErrorUser.getText().trim().equals("") || !jErrorPass.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Niste ispravno popunili sva polja!");
            return;
        }
        Radnik r = new Radnik();
        r.setIme(jtxtIme.getText().trim());
        r.setPrezime(jtxtPrezime.getText().trim());
        r.setUsername(jtxtUser.getText().trim());
        r.setPassword(jtxtIme.getText().trim());
        String ds = jtxtDatumZaposlenja.getText().trim();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        try {
            r.setDatumZaposlenja(sdf.parse(ds));
        } catch (ParseException ex) {
            Logger.getLogger(FMRadnik.class.getName()).log(Level.SEVERE, null, ex);
        }
        r.setStatus("ofline");
        r.setRadnikID(jtxtRadnikID.getText().trim());

        try {
            kontrolor.KontrolorAL.getInstance().dodajRadnika(r);
            fmGlavna.azurirajTabelu(r);
                            JOptionPane.showMessageDialog(this, "Sistem je zapamtio radnika", "Unosenje radnika", JOptionPane.INFORMATION_MESSAGE);

            
        } catch (Exception ex) {
                                      JOptionPane.showMessageDialog(this, "Sistem je ne moze da zapamti radnika", "Unosenje radnika", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jErrorIme;
    private javax.swing.JLabel jErrorPass;
    private javax.swing.JLabel jErrorPrezime;
    private javax.swing.JLabel jErrorUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtxtDatumZaposlenja;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtPass;
    private javax.swing.JTextField jtxtPrezime;
    private javax.swing.JTextField jtxtRadnikID;
    private javax.swing.JTextField jtxtUser;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        jtxtDatumZaposlenja.setText(sdf.format(new Date()));
        jtxtDatumZaposlenja.setEditable(false);
        int broj = 0;
        for (OpstiDomenskiObjekat odo : lista_ranika) {
            Radnik r = (Radnik) odo;
            int a = Integer.parseInt(r.getRadnikID().substring(2, 3));
            if (a > broj) {
                broj = a;
            }
        }
        jtxtRadnikID.setText("R-" + (broj + 1));
                setLocationRelativeTo(null);


    }

    private void postaviDocumentListenerIme() {

        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent documentEvent) {
                validacijaIme();
            }

            @Override
            public void insertUpdate(DocumentEvent documentEvent) {
                validacijaIme();
            }

            @Override
            public void removeUpdate(DocumentEvent documentEvent) {
                validacijaIme();
            }

        };
        jtxtIme.getDocument().addDocumentListener(documentListener);
    }

    private void postaviDocumentListenerPrezime() {
        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent documentEvent) {
                validacijaPrezime();
            }

            @Override
            public void insertUpdate(DocumentEvent documentEvent) {
                validacijaPrezime();
            }

            @Override
            public void removeUpdate(DocumentEvent documentEvent) {
                validacijaPrezime();
            }

        };
        jtxtPrezime.getDocument().addDocumentListener(documentListener);
    }

    private void postaviDocumentListenerUser() {
        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent documentEvent) {
                validacijaUser();
            }

            @Override
            public void insertUpdate(DocumentEvent documentEvent) {
                validacijaUser();
            }

            @Override
            public void removeUpdate(DocumentEvent documentEvent) {
                validacijaUser();
            }

        };
        jtxtUser.getDocument().addDocumentListener(documentListener);
    }

    private void postaviDocumentListenerPass() {
        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent documentEvent) {
                validacijaPass();
            }

            @Override
            public void insertUpdate(DocumentEvent documentEvent) {
                validacijaPass();
            }

            @Override
            public void removeUpdate(DocumentEvent documentEvent) {
                validacijaPass();
            }

        };
        jtxtPass.getDocument().addDocumentListener(documentListener);
    }

    private void validacijaIme() {
        if (jtxtIme.getText().trim().equals("")) {
            jErrorIme.setText("Ovo polje je obavezno");
            jErrorIme.setForeground(Color.red);
        } else {
            jErrorIme.setText("");
            jErrorIme.setForeground(Color.black);
        }

    }

    private void validacijaPass() {
        if (jtxtPass.getText().trim().equals("")) {
            jErrorPass.setText("Ovo polje je obavezno");
            jErrorPass.setForeground(Color.red);
        } else {
            jErrorPass.setText("");
            jErrorPass.setForeground(Color.black);
        }
    }

    private void validacijaUser() {
        if (jtxtUser.getText().trim().equals("")) {
            jErrorUser.setText("Ovo polje je obavezno");
            jErrorUser.setForeground(Color.red);
        } else {
            jErrorUser.setText("");
            jErrorUser.setForeground(Color.black);
        }
    }

    private void validacijaPrezime() {
        if (jtxtPrezime.getText().trim().equals("")) {
            jErrorPrezime.setText("Ovo polje je obavezno");
            jErrorPrezime.setForeground(Color.red);
        } else {
            jErrorPrezime.setText("");
            jErrorPrezime.setForeground(Color.black);
        }
    }
}
