/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Radnik;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontrolor.Kontrolor;
import util.Util;

/**
 *
 * @author Nadin kompjuter
 */
public class FMLogIn extends javax.swing.JFrame {

    /**
     * Creates new form FMLogin
     */
    public FMLogIn() {
        initComponents();
        centrirajFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtKorisnickoIme = new javax.swing.JTextField();
        jbtnUlogujSe = new javax.swing.JButton();
        jpasswordLozinka = new javax.swing.JPasswordField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prijava");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Ime i prezime:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Lozinka:");

        jtxtKorisnickoIme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jbtnUlogujSe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnUlogujSe.setText("Uloguj se");
        jbtnUlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUlogujSeActionPerformed(evt);
            }
        });

        jpasswordLozinka.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnUlogujSe)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtKorisnickoIme)
                            .addComponent(jpasswordLozinka, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpasswordLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jbtnUlogujSe)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUlogujSeActionPerformed
        String korisnickoIme = jtxtKorisnickoIme.getText().trim();
        char[] password = jpasswordLozinka.getPassword();
        if(korisnickoIme.isEmpty() || password.length==0){
                                    JOptionPane.showMessageDialog(this, "Sistem ne može da nađe radnika na osnovu unetih vrednosti", "Prijavljivanje radnika", JOptionPane.ERROR_MESSAGE);
return;
        }
        
        
        String lozinka = "";
        for (int i = 0; i < password.length; i++) {
            lozinka += password[i];
        }
        Radnik r = new Radnik();
        r.setUsername(korisnickoIme);
        r.setPassword(lozinka);
        try {
            Radnik radnik = Kontrolor.getInstance().proveraLogovanja(r);
            if (radnik == null) {
                
                            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe radnika na osnovu unetih vrednosti", "Prijavljivanje radnika", JOptionPane.ERROR_MESSAGE);
                jtxtKorisnickoIme.setText("");
                jpasswordLozinka.setText("");
            }
         else{
                 if(radnik.getStatus().equalsIgnoreCase("online")){
                JOptionPane.showMessageDialog(this, "Ovaj radnik je vec prijavljen na sistem", "Prijavljivanje radnika", JOptionPane.ERROR_MESSAGE);
                return;
                }
                Kontrolor.getInstance().getMapa().put("Ulogovan_radnik", radnik);
                            JOptionPane.showMessageDialog(this, "Uspešno ste se prijavili na sistem", "Prijavljivanje radnika", JOptionPane.INFORMATION_MESSAGE);
                radnik.setStatus("online");
                Kontrolor.getInstance().promeniStatusUlogovanogRadnika(radnik);
                FMGlavna fmg = new FMGlavna();
                fmg.setVisible(true);
                this.setVisible(false);
            }
         } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            this.dispose();
        }
        
       
    
        
        
        
        
        
       
           
           
       
    }//GEN-LAST:event_jbtnUlogujSeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton jbtnUlogujSe;
    private javax.swing.JPasswordField jpasswordLozinka;
    private javax.swing.JTextField jtxtKorisnickoIme;
    // End of variables declaration//GEN-END:variables

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }
    
}
