/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Opstina;
import java.awt.Dialog;
import javax.swing.JOptionPane;
import kontrolor.Kontrolor;

/**
 *
 * @author Nadin kompjuter
 */
public class FMOpstina extends javax.swing.JDialog {

    /**
     * Creates new form FMOpstina
     */
    /* public FMOpstina(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    }*/
    FMKlijent fmKlijent;

    public FMOpstina(Dialog owner, boolean modal) {
        super(owner, modal);
        fmKlijent = (FMKlijent) owner;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNazivOpstine = new javax.swing.JTextField();
        jtxtPostanskiBroj = new javax.swing.JTextField();
        jbtnDodajOpstinu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Naziv opstine:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Postanski broj:");

        jtxtPostanskiBroj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jbtnDodajOpstinu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnDodajOpstinu.setText("Dodaj");
        jbtnDodajOpstinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajOpstinuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnDodajOpstinu)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(36, 36, 36)
                            .addComponent(jtxtNazivOpstine, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(33, 33, 33)
                            .addComponent(jtxtPostanskiBroj))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNazivOpstine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPostanskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addComponent(jbtnDodajOpstinu)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajOpstinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajOpstinuActionPerformed
        String nazivOpstine = jtxtNazivOpstine.getText().trim();
        String postanskiBrojS = jtxtPostanskiBroj.getText().trim();
        if (nazivOpstine.equals("")) {
            JOptionPane.showMessageDialog(this, "Morate uneti naziv opstine.");
            return;
        }
        try {
            int postanskiBroj = Integer.parseInt(postanskiBrojS);
            Opstina o = new Opstina(nazivOpstine, postanskiBroj);
            Kontrolor.getInstance().dodajOpstinu(o);
            fmKlijent.dodajUCombo(o);
      JOptionPane.showMessageDialog(this, "Sistem je zapamtio opštinu", "Unos opštine", JOptionPane.INFORMATION_MESSAGE);

            this.dispose();
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Unesite samo cifre za postanski broj.");
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(this, ex.getMessage());
                   JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti opštinu", "Unos opštine", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jbtnDodajOpstinuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnDodajOpstinu;
    private javax.swing.JTextField jtxtNazivOpstine;
    private javax.swing.JTextField jtxtPostanskiBroj;
    // End of variables declaration//GEN-END:variables

}
