/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Klijent;
import domen.Racun;
import domen.Radnik;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import kontrolor.Kontrolor;
import tabela.TblModelRacun;
import util.Util;

/**
 *
 * @author Nadin kompjuter
 */
public class FMPretragaRacuna extends javax.swing.JDialog {

    /**
     * Creates new form FMPretragaRacuna
     */
    List<Racun> lista_racuna;

    public FMPretragaRacuna(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        lista_racuna = new LinkedList<>();
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbRadnik = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jcbKlijent = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbGodina = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbMesec = new javax.swing.JComboBox<String>();
        jcbDan = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jbtnPronadjiRacune = new javax.swing.JButton();
        jcbUkupnaVrednost = new javax.swing.JComboBox<String>();
        jpnlPronadjeniRacuni = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRacuni = new javax.swing.JTable();
        jpnlFilter = new javax.swing.JPanel();
        jtxtFilter = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jbtnPogledajDetalje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Izaberite parametre za pretragu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jcbRadnik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Radnik koji je izdao racun:");

        jcbKlijent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Klijent:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Godina:");

        jcbGodina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mesec:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Dan:");

        jcbMesec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jcbDan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Ukupna vrednost racuna:");

        jbtnPronadjiRacune.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnPronadjiRacune.setText("Pronadji racune");
        jbtnPronadjiRacune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPronadjiRacuneActionPerformed(evt);
            }
        });

        jcbUkupnaVrednost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jcbGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbMesec, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jcbDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jcbUkupnaVrednost, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbKlijent, 0, 292, Short.MAX_VALUE)))
                        .addGap(53, 53, 53)
                        .addComponent(jbtnPronadjiRacune)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnPronadjiRacune))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jcbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6))
                            .addComponent(jcbKlijent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jcbGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jcbDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jcbMesec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcbUkupnaVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnlPronadjeniRacuni.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Pronadjeni racuni"), "Pronadjeni racuni", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jtblRacuni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtblRacuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblRacuni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtblRacuniMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblRacuni);

        jpnlFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jtxtFilter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Unesite vrednost za filtriranje racuna:");

        javax.swing.GroupLayout jpnlFilterLayout = new javax.swing.GroupLayout(jpnlFilter);
        jpnlFilter.setLayout(jpnlFilterLayout);
        jpnlFilterLayout.setHorizontalGroup(
            jpnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(41, 41, 41)
                .addComponent(jtxtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jpnlFilterLayout.setVerticalGroup(
            jpnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jbtnPogledajDetalje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnPogledajDetalje.setText("Pogledaj detalje");
        jbtnPogledajDetalje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPogledajDetaljeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlPronadjeniRacuniLayout = new javax.swing.GroupLayout(jpnlPronadjeniRacuni);
        jpnlPronadjeniRacuni.setLayout(jpnlPronadjeniRacuniLayout);
        jpnlPronadjeniRacuniLayout.setHorizontalGroup(
            jpnlPronadjeniRacuniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPronadjeniRacuniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnlPronadjeniRacuniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnlFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jbtnPogledajDetalje)
                .addGap(25, 25, 25))
        );
        jpnlPronadjeniRacuniLayout.setVerticalGroup(
            jpnlPronadjeniRacuniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlPronadjeniRacuniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlPronadjeniRacuniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPogledajDetalje))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnlPronadjeniRacuni, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnlPronadjeniRacuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPronadjiRacuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPronadjiRacuneActionPerformed

        Racun racun = popuniRacun();

        List<Racun> lr = null;
        try {
            lr = Kontrolor.getInstance().vratiRacunePoZadatimKriterijumima(racun);

        } catch (Exception e) {
                  JOptionPane.showMessageDialog(this, "Sistem ne može da nađe račune po zadatim vrednostima", "Pretraga računa", JOptionPane.ERROR_MESSAGE);

            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        TblModelRacun tmr = new TblModelRacun(lr);
        jtblRacuni.setModel(tmr);
        lista_racuna = lr;
        PostaviDocumentListenerPretraga();
    }//GEN-LAST:event_jbtnPronadjiRacuneActionPerformed

    private void jtblRacuniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblRacuniMousePressed

        jbtnPogledajDetalje.setEnabled(true);
    }//GEN-LAST:event_jtblRacuniMousePressed

    private void jbtnPogledajDetaljeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPogledajDetaljeActionPerformed

        int red = jtblRacuni.getSelectedRow();
        TblModelRacun tmr = (TblModelRacun) jtblRacuni.getModel();
        Racun r = tmr.vratiRacun(red);
        Kontrolor.getInstance().setAktivnaForma(Util.POPUNI_ZA_RACUN);

        Kontrolor.getInstance().getMapa().put("izabrani_racun", r);
        FMRacun fmr = new FMRacun(this, true);
        fmr.setVisible(true);

    }//GEN-LAST:event_jbtnPogledajDetaljeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnPogledajDetalje;
    private javax.swing.JButton jbtnPronadjiRacune;
    private javax.swing.JComboBox<String> jcbDan;
    private javax.swing.JComboBox<String> jcbGodina;
    private javax.swing.JComboBox<String> jcbKlijent;
    private javax.swing.JComboBox<String> jcbMesec;
    private javax.swing.JComboBox<String> jcbRadnik;
    private javax.swing.JComboBox<String> jcbUkupnaVrednost;
    private javax.swing.JPanel jpnlFilter;
    private javax.swing.JPanel jpnlPronadjeniRacuni;
    private javax.swing.JTable jtblRacuni;
    private javax.swing.JTextField jtxtFilter;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        jbtnPogledajDetalje.setEnabled(false);
        postaviUlogovanogRadnika();
        centrirajFormu();
        popuniComboKlijent();
        popuniComboRadnici();
        popuniComboGodina();
        popuniComboMesec();
        popuniComboDan();
        popuniComboUkupnaVrednost();
        jtblRacuni.setModel(new DefaultTableModel());

    }

    private void postaviUlogovanogRadnika() {
        Radnik radnik = (Radnik) Kontrolor.getInstance().getMapa().get("Ulogovan_radnik");
        this.setTitle(this.getTitle() + " Radnik: " + radnik);
    }

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }

    private void popuniComboKlijent() {
        List<Klijent> lista_klijenata = null;
        try {
            lista_klijenata = Kontrolor.getInstance().vratiListuKlijenata();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Klijent k = new Klijent();
        k.setIme("-");
        k.setPrezime("-");
        k.setJmbg("-");
        lista_klijenata.add(k);
        jcbKlijent.setModel(new DefaultComboBoxModel(lista_klijenata.toArray()));
        jcbKlijent.setSelectedItem(k);
    }

    private void popuniComboRadnici() {
        try {
            List<Radnik> lista_radnika = Kontrolor.getInstance().vratiListuRadnika();
            System.out.println("lista radnika iz baze: " + lista_radnika);
            Radnik r = new Radnik();
            r.setIme("-");
            r.setPrezime("-");
            r.setRadnikID("-");
            lista_radnika.add(r);
            jcbRadnik.setModel(new DefaultComboBoxModel(lista_radnika.toArray()));
            jcbRadnik.setSelectedItem(r);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void popuniComboGodina() {
        for (int i = 2010; i < 2020; i++) {
            jcbGodina.addItem(i + "");
        }
        jcbGodina.addItem("-");
        jcbGodina.setSelectedItem("-");
    }

    private void popuniComboMesec() {
        for (int i = 1; i <= 12; i++) {
            jcbMesec.addItem(i + "");
        }
        jcbMesec.addItem("-");
        jcbMesec.setSelectedItem("-");
    }

    private void popuniComboDan() {
        for (int i = 1; i <= 31; i++) {
            jcbDan.addItem(i + "");
        }
        jcbDan.addItem("-");
        jcbDan.setSelectedItem("-");
    }

    public void PostaviDocumentListenerPretraga() {
        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent documentEvent) {

                documentListenerPretraga();
            }

            @Override
            public void insertUpdate(DocumentEvent documentEvent) {
                documentListenerPretraga();
            }

            @Override
            public void removeUpdate(DocumentEvent documentEvent) {
                documentListenerPretraga();
            }
        };
        jtxtFilter.getDocument().addDocumentListener(documentListener);
    }

    private void documentListenerPretraga() {
        jbtnPogledajDetalje.setEnabled(false);
        String pretraga = jtxtFilter.getText().trim().toUpperCase();

        List<Racun> filtrirana_lista = new LinkedList<>();
        if (lista_racuna == null) {
            return;
        }
        for (Racun r : lista_racuna) {
            if (r.getDatum().toString().toUpperCase().contains(pretraga)
                    || r.getKlijent().toString().toUpperCase().contains(pretraga)
                    || r.getRadnik().toString().toUpperCase().contains(pretraga)
                     || r.getUkupnaVrednost().toString().toUpperCase().contains(pretraga)) {
                filtrirana_lista.add(r);
            }
        }
        TblModelRacun tbr = new TblModelRacun(filtrirana_lista);
        jtblRacuni.setModel(tbr);
    }

    private Racun popuniRacun() {

        Racun racun = new Racun();
     racun.setKlijent((Klijent) jcbKlijent.getSelectedItem());
        racun.setRadnik((Radnik) jcbRadnik.getSelectedItem());
        racun.setDan((String) jcbDan.getSelectedItem());
        racun.setMesec((String) jcbMesec.getSelectedItem());
        racun.setGodina((String) jcbGodina.getSelectedItem());
        racun.setRasponUkupneVrednosti((String) jcbUkupnaVrednost.getSelectedItem());
        return racun;
       
    }

    private void popuniComboUkupnaVrednost() {
        jcbUkupnaVrednost.addItem("0-2000");
        jcbUkupnaVrednost.addItem("2000-4000");
        jcbUkupnaVrednost.addItem("4000-6000");
        jcbUkupnaVrednost.addItem("6000-8000");
        jcbUkupnaVrednost.addItem("8000 i vise");
        jcbUkupnaVrednost.addItem("-");
        jcbUkupnaVrednost.setSelectedItem("-");

    }

}
